#!/usr/bin/env bash
# review-package.sh — Package the diff for a single slice into a single file
# the reviewer can read in one Read. Part of meisijiya-skills' SDD layer,
# adapted from Superpowers subagent-driven-development's `scripts/review-package`.
#
# Why this exists:
#   - OMO task reviewers run as fresh sub-agents (oracle / librarian) and
#     MUST NOT inherit the orchestrator's context.
#   - Pasting `git diff` output inline wastes the orchestrator's context
#     budget AND makes the review prompt fat.
#   - This script writes the diff to a unique path and prints that path;
#     the reviewer does one Read of the file.
#
# Usage:
#   review-package.sh <task-id> <base-sha> <head-sha>
#   review-package.sh <task-id> <base-sha> <head-sha> --output <path>
#
# Output: stdout prints the path of the review-package file. The
# orchestrator embeds this path in the reviewer's dispatch prompt.
#
# Required env / files:
#   - .omo/plans/<slug>.md (or .active_plan pointer)
#   - git repo with commits between BASE and HEAD
#
# Exit codes:
#   0 = package written, path printed
#   1 = usage / args error
#   2 = BASE / HEAD not valid git refs
#   3 = no commits between BASE and HEAD
#   4 = plan file not found

set -euo pipefail

PROG="$(basename "$0")"
usage() {
  cat <<USAGE
Usage: $PROG <task-id> <base-sha> <head-sha> [--output <path>] [--plan <slug>]

Generates a single review-package file containing:
  - commit list between BASE..HEAD (one-line per commit)
  - stat summary (files changed, +/-, by file)
  - full diff with -U10 context

Output path defaults to .omo/sdd/<plan-slug>/task-<id>-diff.patch

CRITICAL: BASE is the commit you recorded BEFORE dispatching the
implementer. NEVER use HEAD~1 — that silently drops all but the last
commit of a multi-commit task.

Exit codes: 0 ok, 1 usage, 2 bad git refs, 3 empty range, 4 plan not found
USAGE
}

# ---------- arg parse ----------
TASK_ID=""
BASE_SHA=""
HEAD_SHA=""
OUT_PATH=""
PLAN_SLUG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUT_PATH="$2"; shift 2 ;;
    --plan)   PLAN_SLUG="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    -*) echo "$PROG: unknown flag $1" >&2; usage; exit 1 ;;
    *)
      if [[ -z "$TASK_ID" ]]; then TASK_ID="$1"
      elif [[ -z "$BASE_SHA" ]]; then BASE_SHA="$1"
      elif [[ -z "$HEAD_SHA" ]]; then HEAD_SHA="$1"
      else echo "$PROG: unexpected positional arg $1" >&2; usage; exit 1
      fi
      shift
      ;;
  esac
done

if [[ -z "$TASK_ID" || -z "$BASE_SHA" || -z "$HEAD_SHA" ]]; then
  echo "$PROG: missing required args" >&2
  usage; exit 1
fi

# ---------- validate git refs ----------
if ! git rev-parse --verify --quiet "${BASE_SHA}^{commit}" >/dev/null 2>&1; then
  echo "$PROG: BASE not a valid git ref: $BASE_SHA" >&2
  exit 2
fi
if ! git rev-parse --verify --quiet "${HEAD_SHA}^{commit}" >/dev/null 2>&1; then
  echo "$PROG: HEAD not a valid git ref: $HEAD_SHA" >&2
  exit 2
fi

# ---------- locate plan ----------
if [[ -z "$PLAN_SLUG" ]]; then
  if [[ -f .omo/plans/.active_plan ]]; then
    PLAN_SLUG="$(cat .omo/plans/.active_plan | tr -d '[:space:]')"
  elif [[ -f .active_plan ]]; then
    PLAN_SLUG="$(cat .active_plan | tr -d '[:space:]')"
  else
    PLAN_FILE="$(ls -1t .omo/plans/*.md 2>/dev/null | head -1 || true)"
    if [[ -z "$PLAN_FILE" ]]; then
      echo "$PROG: no plan file in .omo/plans/ and no --plan given" >&2
      exit 4
    fi
    PLAN_SLUG="$(basename "$PLAN_FILE" .md)"
  fi
fi
PLAN_FILE=".omo/plans/${PLAN_SLUG}.md"
if [[ ! -f "$PLAN_FILE" ]]; then
  echo "$PROG: plan file not found: $PLAN_FILE" >&2
  exit 4
fi

# ---------- range check ----------
if ! COMMIT_RANGE="$(git rev-list --count "${BASE_SHA}..${HEAD_SHA}" 2>/dev/null)"; then
  echo "$PROG: failed to count commits in $BASE_SHA..$HEAD_SHA" >&2
  exit 2
fi
if [[ "$COMMIT_RANGE" == "0" ]]; then
  echo "$PROG: no commits between $BASE_SHA and $HEAD_SHA" >&2
  exit 3
fi

# ---------- derive output path ----------
if [[ -z "$OUT_PATH" ]]; then
  OUT_PATH=".omo/sdd/${PLAN_SLUG}/task-${TASK_ID}-diff.patch"
fi
mkdir -p "$(dirname "$OUT_PATH")"

# ---------- write review-package ----------
PKG_TMP="${OUT_PATH}.tmp.$$"
{
  echo "# Review Package: ${TASK_ID}"
  echo
  echo "_Auto-generated by review-package.sh. Read this entire file once, then return your spec compliance + code quality verdicts._"
  echo
  echo "**Plan:** \`${PLAN_FILE}\`"
  echo "**Task ID:** \`${TASK_ID}\`"
  echo "**Commit range:** \`${BASE_SHA}..${HEAD_SHA}\` (${COMMIT_RANGE} commits)"
  echo "**Package generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "## Commits (most recent first)"
  echo
  echo '```'
  git log --reverse --pretty=format:'%h %ai %s' "${BASE_SHA}..${HEAD_SHA}"
  echo
  echo '```'
  echo
  echo "## Stat summary"
  echo
  echo '```'
  git diff --stat "${BASE_SHA}..${HEAD_SHA}"
  echo '```'
  echo
  echo "## Diff (\`git diff -U10\`)"
  echo
  echo '```diff'
  git diff -U10 "${BASE_SHA}..${HEAD_SHA}"
  echo '```'
  echo
  echo "## Reviewer instructions"
  echo
  echo "Verdict schema (return EXACTLY these two parts in this order):"
  echo
  echo "**Part 1: Spec compliance** — ✅ / ❌ / ⚠️"
  echo "- Compare diff against the brief's acceptance criteria and Interfaces: Produces."
  echo "- Mark ❌ if any acceptance criterion is unmet OR any production symbol is missing."
  echo "- Mark ⚠️ for items you cannot verify from the diff alone (spec compliance requires live inspection of unchanged code or runtime behavior)."
  echo
  echo "**Part 2: Code quality** — Approved / Needs fixes"
  echo "- Strengths (1-3 bullets)"
  echo "- Critical (must-fix, blocks merge)"
  echo "- Important (should-fix before merge)"
  echo "- Minor (nice-to-have)"
  echo "- Each finding MUST cite \`file:line\`."
} > "$PKG_TMP"
mv "$PKG_TMP" "$OUT_PATH"

printf '%s\n' "$OUT_PATH"
