#!/usr/bin/env bash
# slice-progress.sh — Persistent progress ledger for SDD slice execution.
# Part of meisijiya-skills' SDD layer, adapted from Superpowers
# subagent-driven-development's `.superpowers/sdd/progress.md`.
#
# Why this exists:
#   - Conversation memory does not survive compaction. In long slice
#     sequences, the orchestrator (Atlas / Sisyphus) can re-dispatch
#     entire completed task sequences after losing context — the single
#     most expensive failure observed.
#   - OMO has Boulder (`.omo/boulder.json`, schema v2) for session/task
#     state, but Boulder is JSON for the runtime — not human-readable for
#     recovery audits and not formatted as a chronological ledger.
#   - This ledger lives next to OMO plans (`.omo/sdd/<slug>/progress.md`)
#     and provides a recovery map: the commits it names exist in git
#     even when the orchestrator's context no longer remembers creating
#     them.
#
# Usage:
#   slice-progress.sh list [--plan <slug>]
#   slice-progress.sh mark-complete <task-id> <base-sha> <head-sha> [--review-verdict <ok|needs-fixes>] [--plan <slug>]
#   slice-progress.sh mark-blocked <task-id> <reason> [--plan <slug>]
#
# Output: stdout prints the updated ledger path. `list` prints task-status
# rows from the ledger.
#
# Required: jq, a plan file under .omo/plans/<slug>.md

set -euo pipefail

PROG="$(basename "$0")"
usage() {
  cat <<USAGE
Usage:
  $PROG list [--plan <slug>]
  $PROG mark-complete <task-id> <base-sha> <head-sha> [--review-verdict <ok|needs-fixes>] [--plan <slug>]
  $PROG mark-blocked <task-id> <reason> [--plan <slug>]

Appends a structured line to .omo/sdd/<slug>/progress.md (creating the
file if absent). The ledger survives compaction — never trust your own
recollection after /clear, trust this file plus \`git log\`.

Exit codes: 0 ok, 1 usage, 2 plan not found, 4 ledger write failed
USAGE
}

if [[ $# -lt 1 ]]; then
  echo "$PROG: missing subcommand" >&2
  usage; exit 1
fi

# Pre-scan --plan and --help out of $@ at any position so the per-subcommand
# handlers see a clean stream of positionals + their own flags.
PLAN_SLUG=""
ALL_ARGS=("$@")
SUBCOMMAND_ARGS=()
i=0
while [[ $i -lt ${#ALL_ARGS[@]} ]]; do
  a="${ALL_ARGS[$i]}"
  case "$a" in
    --plan)
      if [[ $((i+1)) -ge ${#ALL_ARGS[@]} ]]; then
        echo "$PROG: --plan requires <slug>" >&2
        usage; exit 1
      fi
      PLAN_SLUG="${ALL_ARGS[$((i+1))]}"
      i=$((i+2))
      ;;
    -h|--help)
      usage; exit 0
      ;;
    *)
      SUBCOMMAND_ARGS+=("$a")
      i=$((i+1))
      ;;
  esac
done

# Boundary check below: keeps macOS bash 3.2.57 happy under `set -u`
# (out-of-bounds array access throws "unbound variable"); bash 4.4+
# silently returns empty in the same spot.
[[ ${#SUBCOMMAND_ARGS[@]} -ge 1 ]] || { echo "$PROG: missing subcommand" >&2; usage; exit 1; }
SUBCOMMAND="${SUBCOMMAND_ARGS[0]}"
set -- "${SUBCOMMAND_ARGS[@]:1}"

# ---------- locate plan ----------
if [[ -z "$PLAN_SLUG" ]]; then
  if [[ -f .omo/plans/.active_plan ]]; then
    PLAN_SLUG="$(cat .omo/plans/.active_plan | tr -d '[:space:]')"
  elif [[ -f .active_plan ]]; then
    PLAN_SLUG="$(cat .active_plan | tr -d '[:space:]')"
  else
    PLAN_FILE="$(ls -1t .omo/plans/*.md 2>/dev/null | head -1 || true)"
    if [[ -z "$PLAN_FILE" ]]; then
      echo "$PROG: no plan file in .omo/plans/ and no --plan given" >&2
      exit 2
    fi
    PLAN_SLUG="$(basename "$PLAN_FILE" .md)"
  fi
fi
PLAN_FILE=".omo/plans/${PLAN_SLUG}.md"
[[ -f "$PLAN_FILE" ]] || { echo "$PROG: plan file not found: $PLAN_FILE" >&2; exit 2; }

LEDGER_DIR=".omo/sdd/${PLAN_SLUG}"
LEDGER="${LEDGER_DIR}/progress.md"

# ---------- subcommand dispatch ----------
case "$SUBCOMMAND" in
  list)
    if [[ ! -f "$LEDGER" ]]; then
      echo "$PROG: no ledger yet at $LEDGER — no slices marked" >&2
      exit 0
    fi
    echo "Ledger: $LEDGER"
    echo
    awk -F'|' '/^\| .* \|/ && $2 !~ /^ status/ { print }' "$LEDGER"
    ;;

  mark-complete)
    if [[ $# -lt 3 ]]; then
      echo "$PROG: mark-complete requires <task-id> <base-sha> <head-sha>" >&2
      usage; exit 1
    fi
    TASK_ID="$1"; BASE="$2"; HEAD="$3"; shift 3

    REVIEW_VERDICT="(no review)"
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --review-verdict) REVIEW_VERDICT="$2"; shift 2 ;;
        *) echo "$PROG: unknown arg $1" >&2; usage; exit 1 ;;
      esac
    done

    BASE7="$(git rev-parse --short=7 "$BASE" 2>/dev/null || echo "$BASE")"
    HEAD7="$(git rev-parse --short=7 "$HEAD" 2>/dev/null || echo "$HEAD")"
    TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

    mkdir -p "$LEDGER_DIR"
    if [[ ! -f "$LEDGER" ]]; then
      {
        echo "# SDD Progress Ledger — ${PLAN_SLUG}"
        echo
        echo "_Auto-generated by slice-progress.sh. Append-only; never edit historical rows._"
        echo
        echo "| ts | task_id | status | commits | review | notes |"
        echo "|----|---------|--------|---------|--------|-------|"
      } > "$LEDGER"
    fi

    echo "| ${TS} | ${TASK_ID} | DONE | ${BASE7}..${HEAD7} | ${REVIEW_VERDICT} | _ |" >> "$LEDGER"
    printf '%s\n' "$LEDGER"
    ;;

  mark-blocked)
    if [[ $# -lt 2 ]]; then
      echo "$PROG: mark-blocked requires <task-id> <reason>" >&2
      usage; exit 1
    fi
    TASK_ID="$1"; REASON="$2"; shift 2
    TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    mkdir -p "$LEDGER_DIR"
    if [[ ! -f "$LEDGER" ]]; then
      {
        echo "# SDD Progress Ledger — ${PLAN_SLUG}"
        echo
        echo "_Auto-generated by slice-progress.sh. Append-only; never edit historical rows._"
        echo
        echo "| ts | task_id | status | commits | review | notes |"
        echo "|----|---------|--------|---------|--------|-------|"
      } > "$LEDGER"
    fi
    REASON_SAFE="$(echo "$REASON" | tr '|' '/')"
    echo "| ${TS} | ${TASK_ID} | BLOCKED | _ | _ | ${REASON_SAFE} |" >> "$LEDGER"
    printf '%s\n' "$LEDGER"
    ;;

  *)
    echo "$PROG: unknown subcommand $SUBCOMMAND" >&2
    usage; exit 1
    ;;
esac
